### ISSUE TITLE
Migration to Vue 3 Guide

### ISSUE THREAD

**Issue by bencodezen** [vuejs/docs-next#122]
The following contains a list of all remaining sections of the migration guide to complete.

## Legend

In terms of what the styling means:

- [x] means this has been PR'd and merged
- **Bolded means that this is still an item to do**
- Normal text with a PR at the end means it's currently in review

## Critical

- [x] [RFC #19](https://github.com/vuejs/rfcs/pull/19): Global API Treeshaking - [PR #144](https://github.com/vuejs/docs-next/pull/144)
    - [x] [RFC #29](https://github.com/vuejs/rfcs/pull/29): Global mounting / configuration - [PR #125](https://github.com/vuejs/docs-next/pull/125)
    - [x] [RFC #117](https://github.com/vuejs/rfcs/pull/117): Global API updates - [PR #125](https://github.com/vuejs/docs-next/pull/125)
- [x] [RFC #8](https://github.com/vuejs/rfcs/pull/8): Replace v-bind sync with v-model - [PR #143](https://github.com/vuejs/docs-next/pull/143)

## High

- [x] [RFC #27](https://github.com/vuejs/rfcs/pull/27): Functional and async components API change - [PR #135](https://github.com/vuejs/docs-next/pull/135)
    - [x] [RFC #148](https://github.com/vuejs/rfcs/pull/148): New Async Component API - [PR #139](https://github.com/vuejs/docs-next/pull/139)
- [x] [RFC #31](https://github.com/vuejs/rfcs/pull/31): Component v-model API change - [PR #143](https://github.com/vuejs/docs-next/pull/143)
- [x] [RFC #154](https://github.com/vuejs/rfcs/pull/154): Attribute fallthrough + functional component updates - [PR #141](https://github.com/vuejs/docs-next/pull/141)

## Medium

- [x] [RFC #32](https://github.com/vuejs/rfcs/pull/32): Custom Directive API change - [PR #146](https://github.com/vuejs/docs-next/pull/146)
- [x] **[RFC #105](https://github.com/vuejs/rfcs/pull/105): transition API changes - [Issue #138](https://github.com/vuejs/docs-next/issues/138)**
- [x] [RFC #118](https://github.com/vuejs/rfcs/pull/118): Remove instance events methods (API removal) - [PR #167](https://github.com/vuejs/docs-next/pull/167)
- [x] [RFC #126](https://github.com/vuejs/rfcs/pull/126): Attribute coercion behavior change - [PR #149](https://github.com/vuejs/docs-next/issues/149)
- [x] [RFC #149](https://github.com/vuejs/rfcs/pull/149): Custom Elements Interop Improvements - [PR #177](https://github.com/vuejs/docs-next/pull/177)
- [x] [RFC #20](https://github.com/vuejs/rfcs/pull/20): Slots Unification - [PR #159](https://github.com/vuejs/docs-next/pull/159)
- [x] [RFC #28](https://github.com/vuejs/rfcs/pull/28): Render function API change and library authors - [PR #160](https://github.com/vuejs/docs-next/pull/160)

## Low

- [x] [RFC #95](https://github.com/vuejs/rfcs/pull/95): Remove keycode support in v-on - [PR #158](https://github.com/vuejs/docs-next/pull/158)
- [x] [RFC #97](https://github.com/vuejs/rfcs/pull/97): Remove filters (API removal) - [PR #164](https://github.com/vuejs/docs-next/pull/164)
- [x] [RFC #98](https://github.com/vuejs/rfcs/pull/98): Remove inline-template (API removal) - [PR #183](https://github.com/vuejs/docs-next/pull/183)
- [x] [RFC #111](https://github.com/vuejs/rfcs/pull/111): Remove data object declaration (API removal) - [PR #165](https://github.com/vuejs/docs-next/pull/165)

## New Features

- [x] [RFC #78](https://github.com/vuejs/rfcs/pull/78) Composition API - [PR #161](https://github.com/vuejs/docs-next/pull/161)
- [x] [RFC #112](https://github.com/vuejs/rfcs/pull/112) Teleport - [PR #161](https://github.com/vuejs/docs-next/pull/161)
- [x] [RFC #16](https://github.com/vuejs/rfcs/pull/16): Add "emits" component option - [PR #161](https://github.com/vuejs/docs-next/pull/161)
- [x] Custom Renderer API - [PR #161](https://github.com/vuejs/docs-next/pull/161)
- [x] Fragments - [PR #163](https://github.com/vuejs/docs-next/pull/164)

**Comment by jacekkarczmarczyk** [comment]
Not sure if this is the best place to comment but [FAQ](https://v3.vuejs.org/guide/migration/introduction.html#where-should-i-start-in-a-migration) links to [migration helper](https://github.com/vuejs/vue-migration-helper) which looks quite outdated

**Comment by NataliaTepluhina** [comment]
@jacekkarczmarczyk we will change the link to new migration helper as soon as we have it 😄

**Comment by ota-meshi** [comment]
Hi!
Not included in the RFC, but need to write a migration guide for lifecycle hook changes?

- Removed `beforeDestroy` and `destroyed`
- Added `beforeUnmount` and `unmounted`

**Comment by xPaw** [comment]
There should be a section about `watch` no longer accepting dot-eliminated path strings. https://github.com/vuejs/vue-next/issues/671#issuecomment-579818159

**Comment by posva** [comment]
I think it's worth documenting the removal of `$parent` (and `$children`) as well https://github.com/vuejs/vue-next/issues/2044#issuecomment-687193027

**Comment by NataliaTepluhina** [comment]
Closing this issue as transition API changes were added to docs and linked on Migration Guide - Introduction via https://github.com/vuejs/docs-next/commit/5d02aad4216bd796f18522fc40f483d099120b4a
