### ISSUE TITLE
Migrate Meta content

### ISSUE THREAD

**Issue by bencodezen** [vuejs/docs-next#22]
# Requirements

- [ ]  Migrate the following pages:
    - [ ]  Comparison with Other Frameworks
    - [x]  Join the Vue.js Community!
    - [x]  Meet the Team

**Comment by skirtles-code** [comment]
#976 can be used to track 'Comparison with Other Frameworks'.
